# database for e+He interactions
[
	{"TYPE":"BACKGROUND", "KEY":"He",
	 "MASSRATE": 0.00013714},
	 
	{"TYPE": "ELASTIC",
	 "MTCS": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He -> E + He, Elastic")),
	 # Khrabrov, A. V., & Kaganovich, I. D. (2012).
	 # Electron scattering in helium for Monte Carlo simulations.
	 # Physics of Plasmas, 19(9). DOI: 10.1063/1.4751865
	 "DCSFN": lambda en, p=[2.45, 2.82, 11.98, 5.11, 64.01]: 1\
	 + (p[0]*sqrt(en)-p[1]**2-p[2])/((sqrt(en)-p[1])**2+p[2])\
	 - p[0]*sqrt(en)/((sqrt(en)-p[3])**2+p[4]),
	},
	
	{"TYPE": "EXCITATION", "THRESHOLD": 19.82,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(2S3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 20.62,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(2S1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 20.96,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(2P3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 21.218,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(2P1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 22.719,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(3S3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 22.919,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(3S1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.009,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(3P3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.069,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(3D1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.069,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(3D3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.09,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(3P1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.589,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(4S3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.669,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(4S1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.709,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(4P3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.739,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(4D1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.739,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(4D3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.739,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(4F1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.739,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(4F3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.74,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(4P1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 23.972,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(5S3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.011,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(5S1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.028,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(5P3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.043,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(5D1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.043,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(5D3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.043,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(5FG1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.043,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(5FG3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.046,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(5P1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.169,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(6S3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.191,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(6S1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.201,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(6P3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.209,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(6D1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.209,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(6D3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.21,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(6FGH1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.21,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(6FGH3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.211,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(6P1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.285,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(7S3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.298,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(7S1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.304,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(7P3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.31,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(7D1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.31,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(7D3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.31,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(7FGHI1), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.31,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(7FGHI3), Excitation"))},
	{"TYPE": "EXCITATION", "THRESHOLD": 24.311,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He <-> E + He(7P1), Excitation"))},

	{"TYPE": "IONIZATION", "THRESHOLD": 24.5873, "OPBPARAM": 15.8,
	 "CSEC": (f"{fpath}/He/He_LXCat.txt",
	 dict(search="E + He -> E + E + He+, Ionization"))},
]
